adapt checkpointing for cb
cb calls `acc_f1_metric`, which returns a list of `[acc, f1]`, and this would cause the following error during checkpointing:
```
save_checkpoint(global_step, model, optimizer, lr_scheduler, args, save_dir=os.path.join(args.save, "acc_step{}_acc{:.3}".format(global_step, dev_acc)))
TypeError: unsupported format string passed to list.__format__
```